---
title: "Untitled"
author: "Olatoye"
date: "12/1/2021"
output: pdf_document
---


```{r}
library(readxl)
library(tidyverse)
```

```{r}
mbta <- read_excel("~/Desktop/R/Data-Science-with-R/mbta.xlsx", sheet=1)
mbta
```

```{r}
#mbta <- mbta %>% separate(year, into = c("year", "month"))
#mbta
```

```{r}
#mbta <- mbta %>% pivot_wider(names_from = mode, values_from = passenger)
#mbta
```

```{r}
mbta <- mbta %>% .[, c(1:2, 6:8)]
mbta
```

















```{r}
library(hflights)
data("hflights")
filter(hflights, Year==2011, Month==2, UniqueCarrier=="AA")
```

```{r}
data("hflights")
filter(hflights, Dest %in% c("FLL", "IAH"))
```

```{r}
filter(hflights, between(Distance, 244, 944))
```

```{r}
filter(hflights, Year==2011, Month==4)
filter(hflights, UniqueCarrier==c("AA", "WN"))
```

```{r}
arrange(hflights, Year, Month)
```

```{r}
arrange(hflights, desc(ArrDelay))
```

```{r}
select(hflights, Year, Month, FlightNum, AirTime)[1:4,]
```

```{r}
sel_2 <- select(hflights, tail_num=TailNum)[1:5,]
ren_1 <- rename(hflights, tail_num=TailNum)
```

```{r}
starts <- select(hflights, starts_with("Dep"), starts_with("Arr"))
starts
```

```{r}
vars <- c("Year", "Month", "DaysofMonth", "DaysofMonth", "ArrTime")
s_1 <- select(hflights, one_of(vars))

head(s_1)[1:6,]
```

```{r}
hflights %>%
  select(ends_with("Delay"), Distance, AirTime) %>%
  mutate(time_gain = ArrDelay - DepDelay, speed = Distance / AirTime * 60)
```

```{r}
summarise(hflights, Delay=sum(DepDelay, na.rm=TRUE))
```

```{r}
hflights %>%
  group_by(Year, Month, DayofMonth) %>%
  summarise(delay=mean(DepDelay, na.rm=TRUE))
```

```{r}
hflights %>%
  group_by(Year, Month, DayofMonth) %>%
  summarise(DepDelay=n())
```

```{r}
newDF <- select(hflights, AirTime, ActualElapsedTime, FlightNum, UniqueCarrier)
newDF <- filter(newPat, UniqueCarrier==c("AA", "WN", "CO"))
newDF
```

```{r}
summary(newDF)
```
1

```{r}
sum(is.na(newDF))
```

```{r}
boxplot(AirTime~UniqueCarrier, data = newDF)
boxplot(ActualElapsedTime~UniqueCarrier, data = newDF)
```


```{r}
plot(newDF$AirTime, newDF$ActualElapsedTime, xlab="AirTime", ylab="Actual Elapsed Time", main="Correlation between AirTime and Actual Elapsed")
```


```{r}
AA <- sum(newDF$UniqueCarrier == "AA", na.rm = TRUE)
CO <- sum(newDF$UniqueCarrier == "CO", na.rm = TRUE)
WN <- sum(newDF$UniqueCarrier == "WN", na.rm = TRUE)

message(AA,"   ", CO, "   ", WN)
```


```{r}
#subDF <- select(newDF, AirTime, UniqueCarrier)
#subDF <- filter(subDF, UniqueCarrier==c("AA", "WN", "CO"))

AA_airtime <- filter(newDF, UniqueCarrier == "AA")
AA_airtime <- sum(AA_airtime$AirTime, na.rm = TRUE)


CO_airtime <- filter(newDF, UniqueCarrier == "CO")
CO_airtime <- sum(CO_airtime$AirTime, na.rm = TRUE)

WN_airtime <- filter(newDF, UniqueCarrier == "WN")
WN_airtime <- sum(WN_airtime$AirTime, na.rm = TRUE)

message(AA_airtime, "   ", CO_airtime, "   ", WN_airtime)
```


```{r}
AA_elapsedTime <- filter(newDF, UniqueCarrier == "AA")
AA_elapsedTime <- sum(AA_elapsedTime$ActualElapsedTime, na.rm = TRUE)

CO_elapsedTime <- filter(newDF, UniqueCarrier == "CO")
CO_elapsedTime <- sum(CO_elapsedTime$ActualElapsedTime, na.rm = TRUE)

WN_elapsedTime <- filter(newDF, UniqueCarrier == "WN")
WN_elapsedTime <- sum(WN_elapsedTime$ActualElapsedTime, na.rm = TRUE)

message(AA_elapsedTime, "   ", CO_elapsedTime, "   ", WN_elapsedTime)
```


```{r}
subDf <- data.frame(
  Airline = c("AA", "CO", "WN"),
  AirTime = c(AA_airtime, CO_airtime, WN_airtime),
  ActualElapsedTime = c(AA_elapsedTime, CO_elapsedTime, WN_elapsedTime)
)

subDf
```


```{r}
barplot(subDf$AirTime, xlab = "Airlines", ylab = "AirTime", names.arg = subDf$Airline)
```


```{r}
barplot(subDf$ActualElapsedTime, xlab = "Airlines", ylab = "Actual Elapsed Time", names.arg = subDf$Airline)
```






